version: '3.8'

services:
  web_blue:
    image: minibank_web_test
    build:
      context: .
      dockerfile: Dockerfile.web.test
    ports:
      - "3004:3000"
    env_file:
      - .env.test
    depends_on:
      - postgres_web
    networks:
      - mynetwork

  web_green:
    image: minibank_web_test
    build:
      context: .
      dockerfile: Dockerfile.web.test
    ports:
      - "3005:3000"
    env_file:
      - .env.test
    networks:
      - mynetwork
    depends_on:
      - postgres_web

  postgres_web:
    image: minibank_postgres_web
    build:
      context: .
      dockerfile: Dockerfile.postgres
    env_file:
      - .env.test
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - mynetwork


  nginx:
    image: minibank_nginx_web
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web_blue
      - web_green
    networks:
      - mynetwork


networks:
  mynetwork: